### ISSUE TITLE
Strings::match() should be checked for invalid regex

### ISSUE THREAD

**Issue by enumag** [phpstan/phpstan-nette#108]
I recently added a rule to force using `Strings::match()` instead of `preg_match()` in my project for better API and error handling. However it seems that while PHPStan checks `preg_match` for invalid regular expression (https://github.com/phpstan/phpstan-src/blob/1.9.x/src/Rules/Regexp/RegularExpressionPatternRule.php) the same isn't done for `Strings::match()`.

This is actually very problematic because `Strings::match()` has the regex and haystack arguments swapped which can be easily missed when switching from `preg_match` and I already noticed two cases where one of my developers made that mistake.

How should this be solved? Should we copy the rule from PHPStan here and adjust it? Or should the rule in PHPStan be configurable somehow to allow checking other functions and methods? Or maybe a new `regex-string` type should be added?

**Comment by MartinMystikJonas** [comment]
I would like `regex-string` in core PHPStan

**Comment by enumag** [comment]
That would be my preferred solution as well... Some other languages do have regex as separate type so it would make sense in my opinion.

**Comment by ondrejmirtes** [comment]
Feel free to copy and adjust the rule :)
