### ISSUE TITLE
`Strings::match($pattern, '#([+-])#')` wrongly results in `array{string, '+'}|null`

### ISSUE THREAD

**Issue by janedbal** [phpstan/phpstan-nette#159]
Regular preg_match in PHPStan 1.11.10 does not suffer this issue:

```php
preg_match($s, '#([+-])#', $nativeMatch);
$netteMatch = Strings::match($s, '#([+-])#');

\PHPStan\dumpType($nativeMatch); // array<string>
\PHPStan\dumpType($netteMatch); // array{string, '+'}|null
```

Using version 1.3.6

**Comment by janedbal** [comment]
cc @staabm

**Comment by staabm** [comment]
whats your expected result? is it the same bug as fixed recently on phpstan-src in https://github.com/phpstan/phpstan/issues/11490 ?

**Comment by janedbal** [comment]
Looks like exactly that, thx.

--------

And I dont understand why the PHPStan results of `Strings::match` and `preg_match` differ.

**Comment by staabm** [comment]
The fix was not yet released. Do you compare stable release and latest dev?

**Comment by staabm** [comment]
> And I dont understand why the PHPStan results of Strings::match and preg_match differ.

Compare

https://github.com/phpstan/phpstan-nette/blob/1.1.x/src/Type/Nette/StringsMatchDynamicReturnTypeExtension.php

And

https://github.com/phpstan/phpstan-src/blob/1.12.x/src/Type/Php/PregMatchTypeSpecifyingExtension.php

https://github.com/phpstan/phpstan-src/blob/1.12.x/src/Type/Php/PregMatchParameterOutTypeExtension.php

Note its by-ref arg handling vs. Dynamic return type and `Strings::match` can return null

**Comment by janedbal** [comment]
I compare:
- `phpstan/phpstan-nette 1.3.6` (gives array shape)
- `phpstan/phpstan 1.11.10` (gives generic array)

**Comment by staabm** [comment]
Oh I did not notice this diff. I need to look into details when back on a computer

**Comment by staabm** [comment]
in your example code the arguments are in wrong order

https://phpstan.org/r/a77b2f6a-852b-497a-83d8-fa099fedba7c

**Comment by janedbal** [comment]
Oh god, this typo again. Thx & Sry

**Comment by staabm** [comment]
so this issue can be closed?

**Comment by janedbal** [comment]
The fix feels valid, but I'm not 100% sure it fixes it here. If you are, feel free to close it.

**Comment by janedbal** [comment]
I can confirm this is fixed in latest versions.
