### ISSUE TITLE
Access to an undefined property Nette\Application\UI\Presenter

### ISSUE THREAD

**Issue by aleswita** [phpstan/phpstan-nette#16]
Hi,

any idea, how to fix errors like follow:
``
Access to an undefined property Nette\Application\UI\Presenter::$permission.
``
if I using code below in components?
``
$this->presenter->permission;
``

**Comment by ondrejmirtes** [comment]
Hi, which version of `nette/application` are you using?

**Comment by aleswita** [comment]
v2.4.9

**Comment by aleswita** [comment]
For more details, I'm creating components as multiplier

```php
/**
 * @return Nette\Application\UI\Multiplier
 */
protected function createComponentRow(): Nette\Application\UI\Multiplier
{
	return new Nette\Application\UI\Multiplier(function (int $id): App\Module\Components\Row {
		return new App\Module\Components\Row($id);
	});
}

**Comment by ondrejmirtes** [comment]
There's no property `permission` or Nette\Application\UI\Presenter, so PHPStan is right here: https://github.com/nette/application/blob/v2.4.9/src/Application/UI/Presenter.php

But I probably understand what's wrong with your code - you need to somehow persuade PHPStan that you're relying on the fact that some of your presenters have the `permission` property, probably your BasePresenter or something. So you need to put `@property MyOwnBasePresenter $presenter` in your component (probably `App\Module\Components\Row`?) or your BaseControl.

**Comment by aleswita** [comment]
After added annotation to component, problem solved, tnx for help.
