### ISSUE TITLE
Missing parameter 'featureToggles.narrowPregMatches'.

### ISSUE THREAD

**Issue by MKI-Miro** [phpstan/phpstan-nette#163]
After running composer update I am getting error in Nette app:

`Nette\InvalidArgumentException

Missing parameter 'featureToggles.narrowPregMatches'. )

File: [\vendor\nette\di\src\DI\Helpers.php:127](
`

I have these packages:
phpstan/extension-installer                    1.4.3    
phpstan/phpdoc-parser                          1.30.1 
phpstan/phpstan                                1.12.3   
phpstan/phpstan-nette                          1.3.8   

In config i have:

includes:
	- ../vendor/phpstan/phpstan-nette/extension.neon
	
What should be wrong? or is it bug?

Thank you

**Comment by ondrejmirtes** [comment]
Can you run PHPStan `diagnose` command instead of `analyse`, and paste the output?

If it crashes you can remove the `includes` section from your config.

My suspicion is that you're running a different PHPStan version than you think. The usage of `../vendor` kind of confirms that. You should run the same PHPStan version you installed alongside the extension, not a different one.

**Comment by MKI-Miro** [comment]
`PHPStan diagnose
Note: Using configuration file X:\mania\phpstan.neon.

No rules detected`

When I remove include statement from config, application works.

I the documentation I found that it is not needed. Not sure why I have added it and why it was working :)

So thank you very much for quick reply

**Comment by ondrejmirtes** [comment]
We haven't solved the issue yet.

Pass `-l 5` or the actual level you're using to the diagnose command and paste the output here. Thanks.

**Comment by MKI-Miro** [comment]
PS X:\mania> PHPStan diagnose --level 6
Note: Using configuration file X:\mania\phpstan.neon.
PHP runtime version: 8.2.4
PHP version for analysis: 8.2 (from config.platform.php in composer.json)

PHPStan version: 1.12.3
PHPStan running from:
X:/mania/vendor/phpstan/phpstan

Extension installer:
phpstan/phpstan-nette: 1.3.8

Discovered Composer project roots:
X:/mania
X:\mania

**Comment by ondrejmirtes** [comment]
So it looks like it works for you now!
