### ISSUE TITLE
v0.10 offsetGet in conflict with getComponent

### ISSUE THREAD

**Issue by solcik** [phpstan/phpstan-nette#24]
Hello,

thank you very much for v0.10.
I tried it right away in my project and found a lot of these errors.

```
 ------ ------------------------------------------------------------------------------
  Line   src/....php
 ------ ------------------------------------------------------------------------------
  43     Cannot access offset 'form' on Nette\ComponentModel\IComponent.
  59     Cannot access offset 'form' on Nette\ComponentModel\IComponent.
  86     Cannot access offset 'price' on Nette\ComponentModel\IComponent.
  87     Access to an undefined property Nette\ComponentModel\IComponent::$onSuccess.
 ------ ------------------------------------------------------------------------------
```
These were not shown in 0.9 and I think that conflict is between new handling of offsetGet and current dynamicReturnType for getComponent().

https://github.com/phpstan/phpstan-nette/blob/master/src/Type/Nette/ComponentModelDynamicReturnTypeExtension.php

https://github.com/nette/application/blob/v2.4.12/src/Application/UI/Component.php#L377-L386

If I change arrayAccess to get components to ->getComponent() method calls, errors go away.

**Comment by CZechBoY** [comment]
Yes, I already replaced my codebase with `->getComponent()` calls.
There is no way (and i think there is no plan for that) how to handle dynamic return type extension for array access/set/unset/...

**Comment by CZechBoY** [comment]
@novjan I don't remember, but I replaced it with some regex.

**Comment by novjan** [comment]
Ok, thank you.
Anyway ... do you have some plans about it @ondrejmirtes ?

**Comment by ondrejmirtes** [comment]
I just had an idea how to implement this in an elegant way:

* https://github.com/phpstan/phpstan/commit/41f478dac2f66b673b9dfb6d811336b111a4050c
* https://github.com/phpstan/phpstan-nette/commit/c66d80c5db64ab4a2227c67dac1f573e818fa1eb

Feel free to test it now, it will be released along with PHPStan 0.10.2 in a few days 😊

**Comment by novjan** [comment]
@ondrejmirtes Hi. It looks that it works only for first offset.

This is ok:
```
$this['form']->setDefaults([]);
```

This is ok:
```
$this['form-checkbox']->setDefaultValue(TRUE)
```

This is error:
```
$this['form']['checkbox']->setDefaultValue(TRUE)
```

**Comment by novjan** [comment]
@ondrejmirtes Small example:

```
protected function createComponentFormData()
{
	$isEdit = TRUE;
	$form = new \Nette\Application\UI\Form;
	$form->addText('text');

	if ($isEdit) {
		$form['form']->addRule($form::FILLED); // Call to an undefined method Nette\ComponentModel\IComponent::addRule().
	}

	$data = $form->addContainer('data');
	$data->addText('text2');

	$form['data']['text2']->setDefaultValue('text'); // Cannot access offset 'text2' on Nette\ComponentModel\IComponent.
}
```

**Comment by ondrejmirtes** [comment]
PHPStan has no way of knowing the type of `$form['data']['text2']`. It only works with `createComponentFoo` style factories.

**Comment by ondrejmirtes** [comment]
Use this pattern:

```php
	$data = $form->addContainer('data');
	$text2 = $data->addText('text2');
	$text2->setDefaultValue('text');
```
