### ISSUE TITLE
PresenterGetSessionReturnTypeExtension vs automatic Nette presenter registration

### ISSUE THREAD

**Issue by xificurk** [phpstan/phpstan-nette#25]
Setup:
- `phpstan/phpstan-shim 0.10`
- `phpstan/phpstan-nette 0.10`
- Run composer install with `--optimize-autoloader` flag
- In application configuration enable `Nette\Bridges\ApplicationDI\ApplicationExtension` with (default) settings:
```
application:
  scanComposer: TRUE
  scanFilter: 'Presenter'
```

Result:
Application crashes during container compilation.

Why:
`ApplicationExtension` scans all classes from composer autoloader. One of them is `PresenterGetSessionReturnTypeExtension`, which passes the default filter because it contains `Presenter` in its name. Nette then tries to load it in order to run additional checks via reflection, but that this ends with fatal error: `Interface 'PHPStan\Type\DynamicMethodReturnTypeExtension' not found`.

The error is a result of a combination of multiple factors...
- If you don't use `--optimize-autoloader` flag the error goes away, because `PresenterGetSessionReturnTypeExtension` is not registered in the classmap that Nette uses. So, your app may run locally just fine, but fails in CI (or production) with a very obscure fatal error.
- If you use normal `phpstan` core package instead of `phstan-shim`, you're fine -`DynamicMethodReturnTypeExtension` interface is loadable via composer autoloading, becuase it's not hidden inside phar like in `phpstan-shim`.

The fatal error is not solvable in Nette. You might argue that this phpstan setup is done incorrectly (it should be installed as 3rd party tool outside of application vendor)... Well, yes... unfortunately this setup is quite common in the wild because of the easy setup.

Possible solution:
Rename the extension to not contain `Presenter`? It's ugly, but I don't have a better suggestion.

**Comment by ondrejmirtes** [comment]
Hi, thanks for this awesome report, what an obscure situation 😊 Please test the current dev-master of `phpstan-shim`, we tried this and it should help: https://github.com/phpstan/phpstan-shim/commit/5e9b61d366911012d4c8ddc5b9d97f51f20545af

**Comment by xificurk** [comment]
Thank you for this fix, I can confirm it works!

Note however that this introduces a hard dependency on phar extension into the autoloader - I had to update our php.ini used for tests. It might be a good idea to mention this in readme and/or release notes.

**Comment by ondrejmirtes** [comment]
The need for the extension is alleviated - thanks @lookyman! https://github.com/phpstan/phpstan-shim/commit/5edb6772e6e4983f6f688b25991dc41309a5aa0d
