### ISSUE TITLE
Call to an undefined method Nette\ComponentModel\IComponent::addError()

### ISSUE THREAD

**Issue by japlavaren** [phpstan/phpstan-nette#27]
When I am using code `$form['password']->addError('Error');` what is valid nette error on form component, I am getting `Call to an undefined method Nette\ComponentModel\IComponent::addError()` that is right. There is no `addError` defined in `IComponent`. 
Can I add custom rule to skip this validation?

**Comment by japlavaren** [comment]
I have found solution - add this to `phpstan.neon`:
```
parameters:
    ignoreErrors:
        - '#Call to an undefined method Nette\\ComponentModel\\IComponent::addError\(\)\.#'
```
Think about include this to `phpstan-nette`

**Comment by hrach** [comment]
This is the most annoying error after upgrading to 0.10. I've ignored this too.  I see no easy fix on Phpstan's side. This is  not an optimal design of Nette Forms :(

**Comment by japlavaren** [comment]
I agree. I fond soltion but it tooks me some time. I hopethat this issue
will be indexed by google and maybe help to somebody in future

**Comment by ondrejmirtes** [comment]
Yeah, the form definitions are not easy to find, they are not declared consistently in Nette projects.

**Comment by japlavaren** [comment]
I think it was found properly - error message is that IComponent does not
have method. What is true, form components are IComponents but addError is
not part of IComponent

**Comment by japlavaren** [comment]
I understand that is not easy to say, that `$form['password']` is part of
nette internal code. But phpstan is true that `Nette\Forms\Form` array
acces is returning `IComponent` via.
https://api.nette.org/2.4/source-Forms.Container.php.html#507 But there is
no `addError()` method for `IComponent`. So what I did, I added rule for
ignored errors `- '#Call to an undefined method
Nette\\ComponentModel\\IComponent::addError\(\)\.#'` that is saying,
calling `addError()` on `IComponent` is valid. What is true because all
nette form inputs have parent `Nette\Forms/Controls/BaseControl` (which are
implementing `IControl`) have method `addError()`. So for 99% of cases
there should be added rule `ignoreErrors: - '#Call to an undefined method
Nette\\ComponentModel\\IComponent::addError\(\)\.#'` to
`phpstan/phpstan-nette` package.

**Comment by japlavaren** [comment]
I understand that is not easy to say, that `$form['password']` is part of
nette internal code. But phpstan is true that `Nette\Forms\Form` array
acces is returning `IComponent` via.
https://api.nette.org/2.4/source-Forms.Container.php.html#507 But there is
no `addError()` method for `IComponent`. So what I did, I added rule for
ignored errors `- '#Call to an undefined method
Nette\\ComponentModel\\IComponent::addError\(\)\.#'` that is saying,
calling `addError()` on `IComponent` is valid. What is true because all
nette form inputs have parent `Nette\Forms/Controls/BaseControl` (which are
implementing `IControl`) have method `addError()`. So for 99% of cases
there should be added rule `ignoreErrors: - '#Call to an undefined method
Nette\\ComponentModel\\IComponent::addError\(\)\.#'` to
`phpstan/phpstan-nette` package.

**Comment by ondrejmirtes** [comment]
It's not possible to ignore this error because not all projects contain this error and it would report "unmatched ignored error" by default.

**Comment by japlavaren** [comment]
I did not know about this. Is there any way to add it there but without causing "unmatched ignored error" when there is not this cause?

**Comment by ondrejmirtes** [comment]
Yes, there's `reportUnmatchedIgnoredErrors: true` (by default) but I don't want to change this setting in PHPStan itself.

**Comment by japlavaren** [comment]
I agree that it is not good idea to change it globally. But I was thinking if there is easy way to add rules for ignored errors aside of errors without unmatched ignored error message.

**Comment by ondrejmirtes** [comment]
I just got an idea, there should be a dynamic return type extension for getComponent/offsetGet that says that components accessed on Form are Form's `BaseControl` and not `IComponent` 😊

**Comment by hrach** [comment]
That's a problem, since it could be a `Nette/Forms/Container` or actually some `IComponent` for advanced forms.

**Comment by ondrejmirtes** [comment]
I think we can disregard `IComponent` because it won't be that in 99% of cases but the Container is a problem.
