### ISSUE TITLE
Components\ComponentClass::__construct() does not call parent constructor from Nette\ComponentModel\Component

### ISSUE THREAD

**Issue by bazo** [phpstan/phpstan-nette#32]
i get this error for all components. why is this an error?
the Nette\ComponentModel\Component constructor just checks some legacy stuff
i think this should not be reported as error

**Comment by ondrejmirtes** [comment]
Feel free to ignore it in your `ignoreErrors`.

>  just checks some legacy stuff

This fact might change at any time and I can't monitor changes in Nette source code.
