### ISSUE TITLE
PHP Fatal error:  Uncaught Nette\MemberAccessException: Call to undefined static method Nette\PhpGenerator\Helpers::createObject(). in /var/www/yogahub.online/www/vendor/nette/utils/src/Utils/ObjectHelpers.php:78

### ISSUE THREAD

**Issue by xsuchy09** [phpstan/phpstan-nette#44]
After update Nette to last version with PHP 7.4 support. It is not compatible with last version of https://github.com/nette/php-generator. It is because of this change:
https://github.com/nette/php-generator/commit/6e1cc8dfe3b824abe2439e8eed06183072d4404c

Now `createObject` is part of `Nette\PhpGenerator\Dumper`.

`PHP Fatal error:  Uncaught Nette\MemberAccessException: Call to undefined static method Nette\PhpGenerator\Helpers::createObject(). in /var/www/yogahub.online/www/vendor/nette/utils/src/Utils/ObjectHelpers.php:78
Stack trace:
#0 /var/www/yogahub.online/www/vendor/nette/utils/src/Utils/StaticClass.php(34): Nette\Utils\ObjectHelpers::strictStaticCall('Nette\\PhpGenera...', 'createObject')
#1 /tmp/phpstan/cache/nette.configurator/Container_e4ad11a86e.php(807): Nette\PhpGenerator\Helpers::__callStatic('createObject', Array)
#2 /var/www/yogahub.online/www/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(227): Container_e4ad11a86e->__construct(Array)
#3 /var/www/yogahub.online/www/vendor/phpstan/phpstan/src/DependencyInjection/ContainerFactory.php(77): Nette\Configurator->createContainer()
#4 /var/www/yogahub.online/www/vendor/phpstan/phpstan/src/Command/CommandHelper.php(197): PHPStan\DependencyInjection\ContainerFactory->create('/tmp/phpstan', Array, Array)
#5 /var/www/yogahub.online/www/vendor/phpstan/phpstan/src/Command/Ana in /var/www/yogahub.online/www/vendor/nette/utils/src/Utils/ObjectHelpers.php on line 78`

**Comment by ondrejmirtes** [comment]
Delete the compiled container on disk: /tmp/phpstan/cache/nette.configurator/Container_e4ad11a86e.php and run PHPStan again.

**Comment by xsuchy09** [comment]
Helped. Thanks.
