### ISSUE TITLE
Broken compatibility with Nette 2.x

### ISSUE THREAD

**Issue by fmasa** [phpstan/phpstan-nette#48]
Since stubs for certain Nette 3.0 classes were introduced (such as https://github.com/phpstan/phpstan-nette/commit/336ef25b8e155aac8b6658bc8baada82bcfe97fd#diff-bb9396b9da8def8667dbcf5a2ab44096R6), compatibility with various Nette 2.x packages is broken.

It would be best to at least bump versions in [conflict section](https://github.com/phpstan/phpstan-nette/blob/87aa0f68df743dd820434da0eacfd0dcb59fd541/composer.json#L12). Should I bump these versions or try to revert those Nette 3-only changes?

**Comment by ondrejmirtes** [comment]
Can you specifically list which changes are Nette-3-only and break compatibility?

**Comment by fmasa** [comment]
I actually found just one that affected our codebase. RouteList ArrayAccess API [accepts `Nette\Application\Routers\IRouter`](https://github.com/nette/application/blob/86a28664ca5594a6f97db889fd480cf4cf737218/src/Application/Routers/RouteList.php#L111), but RouteList stub [expects instance of `Nette\Routing\Router`](https://github.com/phpstan/phpstan-nette/blob/87aa0f68df743dd820434da0eacfd0dcb59fd541/stubs/Application/Routers/RouteList.stub#L6), which was introduced in Nette 3.

**Comment by ondrejmirtes** [comment]
Yeah, nothing I can do about this unfortunately, `IRouter` no longer exists in Nette v3 it seems.

Stubs in PHPStan don't have factory that would allow conditional loading of files. I'd recommend you to upgrade to Nette 3 as 2.x is no longer supported https://nette.org/cs/download as of November 2019.
