### ISSUE TITLE
Nette Tester Asserts

### ISSUE THREAD

**Issue by hrach** [phpstan/phpstan-nette#50]
I'm trying to run PhpStan on my test cases. Currently PHPStan doesn't understand any type assertions. For the beginning, it would be great to have just few basic:

- Assert::type()
- Assert::notNull()

**Comment by ondrejmirtes** [comment]
Feel free to send a PR :) You can inspire yourself from https://github.com/phpstan/phpstan-phpunit/tree/master/src/Type/PHPUnit/Assert or from https://github.com/phpstan/phpstan-webmozart-assert/blob/master/src/Type/WebMozartAssert/AssertTypeSpecifyingExtension.php

**Comment by hrach** [comment]
I'm not in position to contribute here, but if is anybody interested, here is a minimal implementation for these two methods:
https://github.com/nextras/orm/commit/79e796f0dad213ba48948e0f42c562ed90b64c88 Feel free to copy that code without any attribution.

**Comment by ondrejmirtes** [comment]
> I'm not in position to contribute here

Why not? it's really simple as you already showed. I'd even accept a PR with just these two methods, which you already implemented.

**Comment by adaamz** [comment]
@adaamz

**Comment by hrach** [comment]
https://github.com/nepada/phpstan-nette-tester
