### ISSUE TITLE
Presenter#sendResponse() is not taken as early terminating method call even it is stated in config file

### ISSUE THREAD

**Issue by dakur** [phpstan/phpstan-nette#51]
I have following code placed in action method of a presenter.

```php
try {
	$identity = $this->accountFacade->authenticate($params);

} catch (AccountNotFound $e) {
	$this->error('', IResponse::S404_NOT_FOUND);

} catch (AccountExpired $e) {
	$template->setFile(__DIR__ . '/...');
	$this->sendTemplate();
}

$this->getUser()->login($identity);
```

Unfortunately phpstan reports `Variable $identity might not be defined.` for the `AccountExpired` catch block. When I added `throw new \Nette\Application\AbortException()` after `$this->sendTemplate()`, it stopped reporting the error.

`sendTemplate()` has `@throw Nette\Application\AbortException` annotated and `sendResponse()` [is listed in early terminated method calls](https://github.com/phpstan/phpstan-nette/blob/fb4bf50cb6d3f704d5296caa73322f978ea8faf6/extension.neon#L24-L33) so I don't know where the problem is.

**Comment by ondrejmirtes** [comment]
`sendTemplate` has to be added to the config file.

**Comment by dakur** [comment]
@ondrejmirtes Is this a note for yourself to do it in phpstan-nette, or an instruction for me to add it to my local config?

**Comment by ondrejmirtes** [comment]
It’s a note for you to send a PR to phpstan-nette 😊

**Comment by dakur** [comment]
👉 #52
