### ISSUE TITLE
RouteList does not accept Route

### ISSUE THREAD

**Issue by arron0** [phpstan/phpstan-nette#55]
Hi,

I have a problem with PhpStan + PhpStan-Nette:
`Nette\Application\Routers\RouteList does not accept Nette\Application\Routers\Route`

Code producing this error:
```php
use Nette\Application\Routers\RouteList;
use Nette\Application\Routers\Route;

$router = new RouteList('v1');
$router[] = new Route('/v1/status', 'Status:default');
```

Workaround for this situation is this:
```php
$router = new RouteList('v1');
$router->offsetSet(null, new Route('/v1/status', 'Status:default'));
```
and it works fine, on one project but on the next one there si different error message:
` Nette\Application\Routers\RouteList::offsetSet() expects Nette\Routing\Router, Nette\Application\Routers\Route given.`

Not sure if it is bug or there is something what I'm doing wrong.

Thank you.

PHP: 7.3
Nette Application: 2.4.13
PhpStan: 0.12.52
Phpstan-Nette: 0.12.9

**Comment by ondrejmirtes** [comment]
I think this comes from differences between Nette 2.4 and 3.0. This package no longer supports Nette 2.4 so you need to upgrade, or ignore this error.

**Comment by arron0** [comment]
Solution was to downgrade after all and ignore some errors because version 0.11.* doesn't support bootstrap files (that was the reason to update in the first place). It may help if 0.12.* is locked to not to install with nette v2.*

**Comment by ondrejmirtes** [comment]
Well the solution definitely isn't to downgrade PHPStan, you'll get a much worse experience that way. The correct way is to stay on 0.12 and ignore this specific error.

The best longterm solution is of course to upgrade your app to Nette 3.0 ;)

**Comment by arron0** [comment]
There were more problems that was solved by downgrade...
```
-- ---------------------------------------------------------------------------
     Error
 -- ---------------------------------------------------------------------------
     Child process error (exit code 255): PHP Fatal error:  Allowed memory
     size of 268435456 bytes exhausted (tried to allocate 8192 bytes) in
     phar:///var/www/html/vendor/phpstan/phpstan/phpstan/src/Type/TypeCombinat
     or.php on line 307
     Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to
     allocate 8192 bytes) in
     phar:///var/www/html/vendor/phpstan/phpstan/phpstan/src/Type/TypeCombinat
     or.php on line 307

 -- ---------------------------------------------------------------------------
```
But it is for another issue...just don't know how to reproduce it with some small piece of code.
