### ISSUE TITLE
False positive on 0.12.15?

### ISSUE THREAD

**Issue by dakorpar** [phpstan/phpstan-nette#63]
![image](https://user-images.githubusercontent.com/9303856/109693232-b9a0ef00-7b89-11eb-8b60-400817aaae3f.png)
see here:
https://github.com/contributte/datagrid/pull/957/checks?check_run_id=2015573206

code:
![image](https://user-images.githubusercontent.com/9303856/109693465-f967d680-7b89-11eb-846c-cb289199735c.png)

I don't think this should be noted as error here...

**Comment by ondrejmirtes** [comment]
Yeah, this is an interesting side-effect of [this change](https://github.com/phpstan/phpstan-nette/commit/0fd695358eb6206a6ec7397722ec3a3d81a21e56)... you can get rid of the error by also having `@param positive-int $offset` above the method. You can also use `@phpstan-param` if you don't want to confuse IDE etc.

I'm gonna keep it open so we can decide if the stub change was a mistake or not... /cc @lulco

**Comment by lulco** [comment]
Yes, that’s exactly kind of errors which should be found by that change. You don’t have any check if offset / limit is positive integer or zero. So the application will fail at this point. I understand it could be annoying (like almost all errors found by phpstan :)) but imho it is good to handle it another way like crashing app.

@ondrejmirtes feel free to remove it, if it is compatible with the base ideas of phpstan

**Comment by dakorpar** [comment]
@lulco then again we're going to far and nette code returns int here so it fails...
![image](https://user-images.githubusercontent.com/9303856/109703380-b01d8400-7b95-11eb-9c93-7726ad6626f9.png)
IMHO this is maybe a bit to much, it's pretty custom param types not really supported by IDE, I wouldn't force that by default... 
sounds good like some additional strictness but maybe to much for regular phpstan-nette

**Comment by ondrejmirtes** [comment]
I guess we could add `@return positive-int|0` to paginator methods as well.

**Comment by dakorpar** [comment]
@ondrejmirtes @lulco any ETA on this?

**Comment by ondrejmirtes** [comment]
If you send a PR that adds a stub for those Paginator methods, I’ll release it right away.

**Comment by dakorpar** [comment]
@ondrejmirtes PR is there
